# Generated by Django 2.1.1 on 2018-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
